// ============================================
// BCA Previous Year Assignments — Data
// ============================================

// --- C Language Course Outcomes ---
const cLanguageCO = {
    CO1: "Design algorithms and choose the right data type and statements for programs.",
    CO2: "Learn the implementation of simple 'C' program, operators and Console I/O function.",
    CO3: "Learning concepts of control statements by writing program control the sequence of the program and give logical outputs.",
    CO4: "Understand the declaration and implementation of arrays and functions.",
    CO5: "Learn the structures declaration, initialization and implementation.",
    CO6: "Understand the file operations, file pointers and importance of pre-processor directives."
};

// --- English Course Outcomes ---
const englishCO = {
    CO1: "Understand the Need and Purpose of Communication.",
    CO2: "Recognize the different signals of nonverbal Communication.",
    CO3: "Enhance and practice advance vocabulary in day-to-day life.",
    CO4: "Understand the word formation in different contexts.",
    CO5: "Develop proficiency in reading skills.",
    CO6: "Activate and reinforce the Writing and critical thinking skills."
};

// --- C Language Assignment 1 (Same for all years) ---
const cLangA1 = {
    sectionA: [
        { q:1, text:"Define the term Pseudo code.", co:"CO1" },
        { q:2, text:"Illustrate the meaning of Expression in C language.", co:"CO1" },
        { q:3, text:"Explain the character set of C language.", co:"CO1" },
        { q:4, text:"Simplify the meaning of Identifiers.", co:"CO1" },
        { q:5, text:"Define the term constant and variable.", co:"CO1" },
        { q:6, text:"List the various steps for problem analysis.", co:"CO1" },
        { q:7, text:"Define keywords? Give example.", co:"CO1" },
        { q:8, text:"Difference between Decision table and Decision tree.", co:"CO1" },
        { q:9, text:"Elaborate the term Symbolic Constants with an example?", co:"CO1" },
        { q:10, text:"Differentiate between an algorithm and a flowchart?", co:"CO1" },
        { q:11, text:"List out the various logical operators.", co:"CO2" },
        { q:12, text:"Differentiate between Formatted and Unformatted I/O functions.", co:"CO2" },
        { q:13, text:"Explain the function of getch() and putchar() with example.", co:"CO2" },
        { q:14, text:"Specify the use of scanf() function?", co:"CO2" },
        { q:15, text:"Describe library functions?", co:"CO2" },
        { q:16, text:"Difference between assignment operator (=) and equality operator (==)?", co:"CO2" },
        { q:17, text:"Compare the prefix and postfix operator?", co:"CO2" },
        { q:18, text:"Illustrate the term operator and operand?", co:"CO2" },
        { q:19, text:"Describe unary operators? Give example.", co:"CO2" },
        { q:20, text:"Write the difference between getch() and puts()?", co:"CO2" },
        { q:21, text:"Differentiate between while and do while loop.", co:"CO3" },
        { q:22, text:"Define Strings? How we can traverse a string?", co:"CO3" },
        { q:23, text:"Give the syntax of if-else statement.", co:"CO3" },
        { q:24, text:"Write the concept of initialization and declaration of strings?", co:"CO3" },
        { q:25, text:"Define String with example.", co:"CO3" },
        { q:26, text:"Mention the use of 'break' and 'continue' statements.", co:"CO3" },
        { q:27, text:"Name three string handling functions available in C.", co:"CO3" },
        { q:28, text:"Describe the difference between Static variable and Automatic variable.", co:"CO3" },
        { q:29, text:"Specify the syntax used for 'for' statement.", co:"CO3" },
        { q:30, text:"Describe the usage of storage classes?", co:"CO3" }
    ],
    sectionB: [
        { q:31, text:"Define flowchart? Demonstrate the various symbol used in flowchart? Explain with example.", co:"CO1" },
        { q:32, text:"Explain the data types in C programming?", co:"CO1" },
        { q:33, text:"Elaborate all types of constants?", co:"CO1" },
        { q:34, text:"Define identifier and also write the rules of identifier.", co:"CO1" },
        { q:35, text:"State the use of algorithms in developing a program? How is it different from flowchart?", co:"CO1" },
        { q:36, text:"Define the following terms with suitable example: i. Expressions ii. Keywords", co:"CO1" },
        { q:37, text:"Describe the different operators used in C with example?", co:"CO2" },
        { q:38, text:"Write the Formatted functions with example?", co:"CO2" },
        { q:39, text:"Discuss the Conditional operator or explain Ternary Operator with example?", co:"CO2" },
        { q:40, text:"Differentiate between relational and logical operators used in C?", co:"CO2" },
        { q:41, text:"Describe the five arithmetic operators in C?", co:"CO2" },
        { q:42, text:"Explain Unformatted I/O functions with example?", co:"CO2" },
        { q:43, text:"Explain the various decision making statements in C language.", co:"CO3" },
        { q:44, text:"Demonstrate the various storage classes in C programming with an example?", co:"CO3" },
        { q:45, text:"Paraphrase the loop control statements or iteration statements of C in detail.", co:"CO3" },
        { q:46, text:"Explain the operations performed on string with an example?", co:"CO3" },
        { q:47, text:"Define the Switch-Case statement with example?", co:"CO3" },
        { q:48, text:"Write the Go to and continue statement?", co:"CO3" }
    ]
};

// --- C Language Assignment 2 (Same for all years) ---
const cLangA2 = {
    sectionA: [
        { q:1, text:"What is an array? How to declare and initialize an array?", co:"CO4" },
        { q:2, text:"Explain the concept of functions in C with example.", co:"CO4" },
        { q:3, text:"What is recursion? Give an example.", co:"CO4" },
        { q:4, text:"How to pass an array to a function?", co:"CO4" },
        { q:5, text:"Explain the difference between call by value and call by reference.", co:"CO4" },
        { q:6, text:"Write a program to find factorial using recursion.", co:"CO4" },
        { q:7, text:"Explain the concept of multidimensional array with example.", co:"CO4" },
        { q:8, text:"What are the advantages of using functions in C?", co:"CO4" },
        { q:9, text:"Explain the scope of variables in C.", co:"CO4" },
        { q:10, text:"What is the difference between array and pointer?", co:"CO4" },
        { q:11, text:"Define structure. Write the syntax for structure declaration with an example.", co:"CO5" },
        { q:12, text:"What do you mean by unions? How memory is allocated to unions?", co:"CO5" },
        { q:13, text:"Mention the difference between structure and union with example.", co:"CO5" },
        { q:14, text:"List the two ways of passing structure to a function.", co:"CO5" },
        { q:15, text:"Specify the different ways to access members in a structure.", co:"CO5" },
        { q:16, text:"Write the significance of structure and union in C.", co:"CO5" },
        { q:17, text:"Demonstrate the actual parameters and formal parameters? Illustrate with example.", co:"CO5" },
        { q:18, text:"Explain the concept of pointers in C.", co:"CO5" },
        { q:19, text:"How are pointers declared and initialized?", co:"CO5" },
        { q:20, text:"Write notes on pointers and its uses.", co:"CO5" },
        { q:21, text:"Explain the following file functions with example: a) Fseek() b) Fopen() c) Fclose() d) Ftell()", co:"CO6" },
        { q:22, text:"Write notes on processing a data file.", co:"CO6" },
        { q:23, text:"Explain the operating modes of files.", co:"CO6" },
        { q:24, text:"Write the various file handling functions in C language.", co:"CO6" },
        { q:25, text:"List the various types of errors occur during file operations.", co:"CO6" },
        { q:26, text:"Explain the concept of file pointer in C.", co:"CO6" },
        { q:27, text:"How to read data from a file in C?", co:"CO6" },
        { q:28, text:"How to write data to a file in C?", co:"CO6" },
        { q:29, text:"What is the difference between text file and binary file?", co:"CO6" },
        { q:30, text:"Explain the importance of pre-processor directives in C.", co:"CO6" }
    ],
    sectionB: [
        { q:31, text:"Write a program to add two matrices using arrays.", co:"CO4" },
        { q:32, text:"Write a program to find the sum of n numbers using function.", co:"CO4" },
        { q:33, text:"Write a program to reverse a string using recursion.", co:"CO4" },
        { q:34, text:"Write a program to find the largest element in an array.", co:"CO4" },
        { q:35, text:"Write a program to calculate factorial using function.", co:"CO4" },
        { q:36, text:"Write a program to sort an array in ascending order.", co:"CO4" },
        { q:37, text:"Write a program to store and display employee information using structure.", co:"CO5" },
        { q:38, text:"Write a program to demonstrate the use of union.", co:"CO5" },
        { q:39, text:"Write a program to pass structure to a function.", co:"CO5" },
        { q:40, text:"Write a program to demonstrate the use of pointers.", co:"CO5" },
        { q:41, text:"Write a program to swap two numbers using pointers.", co:"CO5" },
        { q:42, text:"Write a program to demonstrate pointer to structure.", co:"CO5" },
        { q:43, text:"Write a program to read data from a file and display it on screen.", co:"CO6" },
        { q:44, text:"Write a program to save employee details in a file using file handling.", co:"CO6" },
        { q:45, text:"Write a program to append data to an existing file.", co:"CO6" },
        { q:46, text:"Write a program to copy data from one file to another.", co:"CO6" },
        { q:47, text:"Write a program to count the number of characters, words and lines in a file.", co:"CO6" },
        { q:48, text:"Write a program to demonstrate fseek() and ftell() functions.", co:"CO6" }
    ]
};

// ============================================
// ENGLISH — Year 2022 — Assignment 2
// ============================================
const eng2022A2 = {
    sectionA: [
        { q:1, text:"What are prefixes? Give two examples.", co:"CO4" },
        { q:2, text:"Add prefix to the words: (i) responsible (ii) understand", co:"CO4" },
        { q:3, text:"Use -able as suffix to make two meaningful words.", co:"CO4" },
        { q:4, text:"What is collocation? Give two examples.", co:"CO4" },
        { q:5, text:`"Vocabulary enhances communication skills." Discuss.`, co:"CO4" },
        { q:6, text:"Fill suitable prefix: (i) The situation was ___ predictable. (ii) He is ___ active in class.", co:"CO4" },
        { q:7, text:"Give two examples of Adjective + Noun collocation.", co:"CO4" },
        { q:8, text:"Use over- as prefix to make two meaningful words.", co:"CO4" },
        { q:9, text:"Fill suitable suffix: (i) The result was ___. (surprise) (ii) She is a ___ woman. (beauty)", co:"CO4" },
        { q:10, text:"What are suffixes? Give two examples.", co:"CO4" },
        { q:11, text:"What is the importance of reading?", co:"CO5" },
        { q:12, text:"How does reading help in learning?", co:"CO5" },
        { q:13, text:"How does reading improve writing skills?", co:"CO5" },
        { q:14, text:"What are the different types of reading?", co:"CO5" },
        { q:15, text:"What is the purpose of reading?", co:"CO5" },
        { q:16, text:"What is critical reading?", co:"CO5" },
        { q:17, text:"How to read effectively?", co:"CO5" },
        { q:18, text:"What is the role of reading in academics?", co:"CO5" },
        { q:19, text:"Why do we read?", co:"CO5" },
        { q:20, text:"How does reading help in job preparation?", co:"CO5" },
        { q:21, text:"What is comprehension?", co:"CO6" },
        { q:22, text:"How to develop good communication skills?", co:"CO6" },
        { q:23, text:"Why is writing important?", co:"CO6" },
        { q:24, text:"What is the importance of vocabulary in writing?", co:"CO6" },
        { q:25, text:"How to write a good essay?", co:"CO6" },
        { q:26, text:"What are the steps of writing?", co:"CO6" },
        { q:27, text:"What is the importance of editing?", co:"CO6" },
        { q:28, text:"What is the difference between formal and informal writing?", co:"CO6" },
        { q:29, text:"How to improve grammar?", co:"CO6" },
        { q:30, text:"Why is practice important in writing?", co:"CO6" }
    ],
    sectionB: [
        { q:31, text:"Explain collocation with types and examples.", co:"CO4" },
        { q:32, text:"Identify 6 prefixes in the following paragraph. Make 2 meaningful words by using those prefixes.", co:"CO4",
          passage:"The students were asked to rethink their answers. The initial response was incorrect. They needed to rewrite the assignment. The teacher was unhappy with the results. She advised them to review the lessons. They were determined to improve." },
        { q:33, text:"Do as directed:", co:"CO4",
          subs:["a. Use '-ence' as suffix to make two meaningful words.","b. Use 'sub-' as prefix to make two meaningful words.","c. The movie was very ___. (excite) (Use suitable suffix)","d. He ___ the instructions clearly. (stand) (Use suitable prefix)","e. The decision was ___. (avoid) (Use suitable suffix)","f. She was very ___ to help. (will) (Use suitable suffix)"] },
        { q:34, text:"Identify 6 prefixes in the following paragraph. Make 2 meaningful words by using those prefixes.", co:"CO4",
          passage:"The team decided to reorganize the work. They were unhappy with the previous plan. They wanted to reallocate the tasks. The leader was proactive in finding solutions. They worked together to overcome the challenges. The project was a success." },
        { q:35, text:"Identify 6 suffixes in the following paragraph. Make 2 meaningful words by using those suffixes.", co:"CO4",
          passage:"The garden was beautiful with colourful flowers. The children were happily playing. The peaceful environment was relaxing. Everyone felt joyful and calm. The wonderful weather made the day perfect." },
        { q:36, text:"What are prefix and suffix? Give four examples of each.", co:"CO4" },
        { q:37, text:"Discuss the role of reading skills in English language.", co:"CO5" },
        { q:38, text:"How can we improve our reading skills? Explain with steps.", co:"CO5" },
        { q:39, text:"What is active reading? Explain its techniques.", co:"CO5" },
        { q:40, text:"Explain the different reading skills in detail.", co:"CO5" },
        { q:41, text:"What are the gears of reading? Explain.", co:"CO5" },
        { q:42, text:"What skills are required for reading?", co:"CO5" },
        { q:43, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Kindness is a great quality. It makes people happy. A kind person always helps others. Kindness creates a positive environment. We should always be kind to everyone. It does not cost anything but means a lot.",
          subs:["a) What is kindness?","b) How does kindness help?","c) Why should we be kind?","d) What does kindness create?","e) Why is kindness important?"] },
        { q:44, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Hard work is the secret of success. It helps us achieve our goals. There is no substitute for hard work. It brings confidence and experience. We should always work hard and never give up.",
          subs:["a) What is the secret of success?","b) How does hard work help?","c) What does hard work bring?","d) What should we never do?","e) Why is hard work important?"] },
        { q:45, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Honesty is the best policy. It builds trust and respect. Honest people are loved and admired. We should always speak the truth. Honesty makes us good human beings.",
          subs:["a) What is the best policy?","b) What does honesty build?","c) How are honest people?","d) What should we always speak?","e) What does honesty make us?"] },
        { q:46, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Teamwork is working together to achieve a goal. It is important in school, work, and life. It helps us to share ideas and work faster. Teamwork teaches us to cooperate and helps us to build strong relationships.",
          subs:["a) What is teamwork?","b) Where is teamwork important?","c) How does teamwork help?","d) What does teamwork teach us?","e) What does teamwork help us build?"] },
        { q:47, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Goals are what we want to achieve in life. They give us direction and purpose. We should set realistic goals. Hard work and focus help us reach our goals. Goals keep us motivated and determined.",
          subs:["a) What are goals?","b) What do goals give us?","c) What kind of goals should we set?","d) What helps us reach our goals?","e) What do goals keep us?"] },
        { q:48, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Reading books is a good habit. It gives us knowledge and information. It improves our language and vocabulary. It also relaxes our mind. We should read books every day.",
          subs:["a) What is a good habit?","b) What does reading give us?","c) What does reading improve?","d) How does reading relax our mind?","e) How often should we read?"] }
    ]
};

// ============================================
// ENGLISH — Year 2023 — Assignment 2
// ============================================
const eng2023A2 = {
    sectionA: [
        { q:1, text:"What is the difference between prefix and suffix?", co:"CO4" },
        { q:2, text:"Add prefix to the words: (i) legal (ii) regular", co:"CO4" },
        { q:3, text:"Use -ment as suffix to make two meaningful words.", co:"CO4" },
        { q:4, text:"Define collocation with two examples.", co:"CO4" },
        { q:5, text:`"Vocabulary is the key to communication." Discuss.`, co:"CO4" },
        { q:6, text:"Fill suitable prefix: (i) The document was ___ signed. (ii) He was ___ qualified for the job.", co:"CO4" },
        { q:7, text:"Give two examples of Verb + Noun collocation.", co:"CO4" },
        { q:8, text:"Use un- as prefix to make two meaningful words.", co:"CO4" },
        { q:9, text:"Fill suitable suffix: (i) The story was very ___. (interest) (ii) He was a very ___ man. (success)", co:"CO4" },
        { q:10, text:"Give two examples of prefixes.", co:"CO4" },
        { q:11, text:"What is the role of reading in education?", co:"CO5" },
        { q:12, text:"How does reading help in communication?", co:"CO5" },
        { q:13, text:"What are the benefits of regular reading?", co:"CO5" },
        { q:14, text:"What is the purpose of reading comprehension?", co:"CO5" },
        { q:15, text:"What is skimming and scanning?", co:"CO5" },
        { q:16, text:"What is the difference between intensive and extensive reading?", co:"CO5" },
        { q:17, text:"How can we improve reading fluency?", co:"CO5" },
        { q:18, text:"Why is vocabulary important for reading?", co:"CO5" },
        { q:19, text:"What is the SQ3R technique of reading?", co:"CO5" },
        { q:20, text:"How does reading help in developing critical thinking?", co:"CO5" },
        { q:21, text:"What is reading comprehension?", co:"CO6" },
        { q:22, text:"How can we improve our communication skills?", co:"CO6" },
        { q:23, text:"What is the importance of good communication?", co:"CO6" },
        { q:24, text:"How to improve writing skills?", co:"CO6" },
        { q:25, text:"What is the difference between paraphrasing and summarizing?", co:"CO6" },
        { q:26, text:"What is editing in writing?", co:"CO6" },
        { q:27, text:"What is the importance of grammar in writing?", co:"CO6" },
        { q:28, text:"How to write a good paragraph?", co:"CO6" },
        { q:29, text:"What is the role of revision in writing?", co:"CO6" },
        { q:30, text:"Why is practice important for writing skills?", co:"CO6" }
    ],
    sectionB: [
        { q:31, text:"Explain collocation with its types and examples.", co:"CO4" },
        { q:32, text:"Identify 6 prefixes in the following paragraph. Make 2 meaningful words using those prefixes.", co:"CO4",
          passage:"The manager asked the team to reexamine the project. The initial plan was incomplete. They had to rework many sections. Some members were unsure about the changes. The manager was proactive in solving problems. They were determined to overcome difficulties." },
        { q:33, text:"Do as directed:", co:"CO4",
          subs:["a. Use '-tion' as suffix to make two meaningful words.","b. Use 'inter-' as prefix to make two meaningful words.","c. Her speech was very ___. (inspire) (Use suitable suffix)","d. He ___ the rules completely. (understand) (Use suitable prefix)","e. The task was ___. (complete) (Use suitable prefix)","f. She showed great ___. (courage) (Use suitable suffix)"] },
        { q:34, text:"Identify 6 prefixes in the following paragraph. Make 2 meaningful words using those prefixes.", co:"CO4",
          passage:"The students were excited about the international competition. They had to prepare for the event. Their teachers were supportive. They decided to cooperate with each other. They wanted to showcase their talents. The inter-school competition was a great opportunity." },
        { q:35, text:"Identify 6 suffixes in the following paragraph. Make 2 meaningful words using those suffixes.", co:"CO4",
          passage:"The teacher was very helpful. She gave clear instructions. The students were excited about the project. They worked carefully on their assignments. The completed work was impressive. Everyone felt satisfied with their achievement." },
        { q:36, text:"What are prefix and suffix? Give four examples of each.", co:"CO4" },
        { q:37, text:"Why are reading skills important in English? Discuss.", co:"CO5" },
        { q:38, text:"How can we improve reading skills? Explain with steps.", co:"CO5" },
        { q:39, text:"What is active reading? Explain with techniques.", co:"CO5" },
        { q:40, text:"Explain the different reading skills in detail.", co:"CO5" },
        { q:41, text:"What are the gears of reading? Explain.", co:"CO5" },
        { q:42, text:"What skills are required to be a good reader?", co:"CO5" },
        { q:43, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Water is essential for all living beings. It is used for drinking, cooking, and cleaning. Water is also important for agriculture. We should not waste water. We should save rainwater. We should keep rivers and lakes clean.",
          subs:["a) Why is water essential?","b) What are the uses of water?","c) Why should we save water?","d) How can we save water?","e) Why should we keep rivers clean?"] },
        { q:44, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Forests are important for our planet. They give us oxygen and absorb carbon dioxide. They are home to many animals and birds. We should protect forests. We should plant more trees. Deforestation is harmful to the environment.",
          subs:["a) Why are forests important?","b) What do forests give us?","c) Why should we protect forests?","d) What is deforestation?","e) How can we protect forests?"] },
        { q:45, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"A healthy lifestyle is important for everyone. It includes eating healthy food, exercising daily, and sleeping well. We should avoid junk food and stress. We should drink enough water and stay active. A healthy lifestyle keeps us fit and happy.",
          subs:["a) What is a healthy lifestyle?","b) What does a healthy lifestyle include?","c) Why should we avoid junk food?","d) Why is exercise important?","e) How does a healthy lifestyle help us?"] },
        { q:46, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Technology has changed our lives. It makes our work easier and faster. We can communicate with anyone anywhere. Technology helps in education, health, and business. We should use technology wisely. It has made the world a better place.",
          subs:["a) How has technology changed our lives?","b) What are the benefits of technology?","c) How does technology help in education?","d) How should we use technology?","e) Why is technology important in business?"] },
        { q:47, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Friendship is a beautiful relationship. It brings joy and happiness in life. A true friend always helps us in difficult times. Friendship teaches us to be kind. We should always value our friends. Friendship makes life meaningful.",
          subs:["a) What is friendship?","b) How does friendship help us?","c) What does friendship teach us?","d) Why should we value our friends?","e) How does friendship make life meaningful?"] },
        { q:48, text:"Read the passage and answer the questions:", co:"CO6",
          passage:"Time management is the key to success. It helps us to complete our work on time. We should set goals and make a schedule. We should not waste time on useless things. Good time management leads to a successful life.",
          subs:["a) What is time management?","b) Why is time management important?","c) How can we manage time better?","d) What should we not waste time on?","e) What does good time management lead to?"] }
    ]
};

// ============================================
// ENGLISH — Year 2024 — Assignment 2
// ============================================
const eng2024A2 = {
    sectionA: [
        { q:1, text:"What do you mean by Suffix with example?", co:"CO4" },
        { q:2, text:"Add prefix to the words: (i) agree (ii) biography", co:"CO4" },
        { q:3, text:"Use -dom as suffix to make two meaningful words.", co:"CO4" },
        { q:4, text:"Define Collocation with at least 2 examples.", co:"CO4" },
        { q:5, text:`"We should use vocabulary as per the need of the audience". Discuss.`, co:"CO4" },
        { q:6, text:"Fill suitable prefix: (i) The newspaper led a campaign against social ___ (justice) (ii) Tarun was ___ (able) to complete his assignment on time.", co:"CO4" },
        { q:7, text:"Give two examples of Adverb+ Adjective collocation.", co:"CO4" },
        { q:8, text:"Use mis- as prefix to make two meaningful words.", co:"CO4" },
        { q:9, text:"Fill suitable suffix: (i) He was acting in a very ___ way. (child) (ii) Some of the Indian cities are dreadfully ___. (crowd)", co:"CO4" },
        { q:10, text:"What do you mean by Prefix with example.", co:"CO4" },
        { q:11, text:"What is the purpose of analysing a text while reading?", co:"CO5" },
        { q:12, text:"Explain the role of reading in enhancing communication skills.", co:"CO5" },
        { q:13, text:"How does regular practice improve reading skills?", co:"CO5" },
        { q:14, text:"In what way does reading improve vocabulary?", co:"CO5" },
        { q:15, text:"What is one challenge you might face when reading?", co:"CO5" },
        { q:16, text:"Name one gear involved in the reading process.", co:"CO5" },
        { q:17, text:"How does reading help in increasing our fluency?", co:"CO5" },
        { q:18, text:"Why is critical thinking important in the reading process?", co:"CO5" },
        { q:19, text:"How can taking notes while reading help?", co:"CO5" },
        { q:20, text:"Why is it helpful to discuss what you read with others?", co:"CO5" },
        { q:21, text:"What is a comprehension?", co:"CO6" },
        { q:22, text:"What can we do to develop good communication skills?", co:"CO6" },
        { q:23, text:"Why is vocabulary knowledge crucial for reading comprehension?", co:"CO6" },
        { q:24, text:"What are the benefits of discussing a text after reading?", co:"CO6" },
        { q:25, text:"In what ways do communication skills contribute to the development of effective reading skills?", co:"CO6" },
        { q:26, text:"How can you solve comprehension?", co:"CO6" },
        { q:27, text:"What is the importance of reading in comprehension?", co:"CO6" },
        { q:28, text:"Discuss the process of comprehension.", co:"CO6" },
        { q:29, text:`"Comprehension leads to effective reading". Discuss.`, co:"CO6" },
        { q:30, text:"What is the role of Revising and Editing in comprehension?", co:"CO6" }
    ],
    sectionB: [
        { q:31, text:"What do you mean by Collocation. Explain its types with examples.", co:"CO4" },
        { q:32, text:"Identify 6 prefix in the following paragraph. Make 2 meaningful words by using those prefixes.", co:"CO4",
          passage:"When Jane was asked to rewrite the report, she knew it would be a challenging task. Her initial attempt had been misunderstood by her colleagues, leading to a discrepancy in the final results. She decided to reevaluate the data carefully, making sure to prevent any further inaccuracies. Jane was undeterred by the overwhelming workload and remained proactive in her approach. She believed that by understanding the root causes of the issues, she could correct the problems and ensure a successful outcome. After a thorough review, she felt a great sense of achievement and knew that her overall efforts had been worth it." },
        { q:33, text:"Do as directed:", co:"CO4",
          subs:["a. Use 'less' as suffix to make two meaningful words.","b. Use 'dis' as prefix to make two meaningful words.","c. Everybody enjoys the companionship of ___ people. (humour) (Use suitable suffix)","d. He decided to ___ the offer I gave him. (consider) (Use suitable prefix)","e. His homework is always ___. (complete) (Use suitable prefix)","f. She did not keep her ___ with her. (eat) (Use suitable suffix)"] },
        { q:34, text:"Identify 6 prefix in the following paragraph. Make 2 meaningful words by using those prefixes.", co:"CO4",
          passage:"In the small town of Greenfield, residents were excited about the reopening of the local park. After months of unexpected delays, the renovation was finally complete. The community was eager to revisit their favourite spots and discover the new features that had been added. Families planned to prepare for a grand picnic on the first weekend. The park now had a more cohesive design with updated play areas and interesting new walking trails. Everyone was hopeful that these improvements would overcome the issues from before and bring more joy to the town." },
        { q:35, text:"Identify 6 suffix in the following paragraph. Make 2 meaningful words by using those suffixes.", co:"CO4",
          passage:"In the beautiful park, children were happily playing with their colourful kites. The playground was filled with laughter and the excited shouts of kids enjoying their time. Nearby, a group of friendly adults were having a picnic under the shade of a large tree. The refreshing breeze made the afternoon feel even more pleasant. The park's cleanliness was evident, and it was clear that the dedicated staff worked hard to keep the area in top condition. Everyone appreciated the safe and welcoming environment, which made the day enjoyable for all." },
        { q:36, text:"What do you mean by Suffix and Prefix? Give four examples of each.", co:"CO4" },
        { q:37, text:"Reading skills is one of the important skills in English Language. Discuss.", co:"CO5" },
        { q:38, text:"How can we improve our reading skills. Explain with 5 steps.", co:"CO5" },
        { q:39, text:"Describe the process of active reading. Provide specific techniques that readers can use to engage more deeply with texts and enhance their comprehension.", co:"CO5" },
        { q:40, text:"Discuss effective reading skills in detail.", co:"CO5" },
        { q:41, text:"Discuss the gears of reading in detail.", co:"CO5" },
        { q:42, text:"What skills are required for reading?", co:"CO5" },
        { q:43, text:"Read the following passage and answer the questions given in the end.", co:"CO6",
          passage:"Sleep is essential for maintaining good health and well-being. During sleep, the body undergoes various restorative processes, including muscle repair, hormone regulation, and memory consolidation. Adults typically need between 7 to 9 hours of sleep per night to function optimally. Insufficient sleep can lead to a range of health issues, such as weakened immune function, weight gain, and mental health problems like anxiety and depression. The quality of sleep is just as important as the quantity; deep sleep is crucial for recovery and cognitive functions. To improve sleep quality, it's advisable to establish a regular sleep schedule, create a calming bedtime routine, and design a restful sleeping environment. Factors such as light, noise, and temperature can significantly impact how well we sleep. Limiting screen time before bed is also beneficial, as blue light emitted from devices can interfere with the body's natural sleep-wake cycle. By prioritizing sleep and adopting healthy sleep habits, individuals can enhance their overall health and productivity.",
          subs:["a) Why is sleep considered essential for health?","b) What are two restorative processes that occur during sleep?","c) How many hours of sleep do adults typically need?","d) List two health issues associated with insufficient sleep.","e) What are two suggestions for improving sleep quality?","f) What impact does a regular sleep schedule have on sleep?"] },
        { q:44, text:"Read the following passage and answer the questions given in the end.", co:"CO6",
          passage:"The water cycle is a continuous process through which water circulates between the earth's oceans, atmosphere, and land. This cycle involves several stages: evaporation, condensation, precipitation, and collection. Water evaporates from the surface of oceans, lakes, and rivers, turning into water vapor. As the vapor rises, it cools and condenses to form clouds. When the clouds become heavy, the water falls back to the earth as precipitation, such as rain or snow. This water then collects in various bodies of water, such as lakes, rivers, and oceans, where it can evaporate again, continuing the cycle. The water cycle is vital for maintaining ecosystems, as it helps distribute fresh water and supports plant and animal life. Additionally, it plays a crucial role in regulating the earth's climate. Understanding the water cycle is essential for addressing issues like water scarcity and climate change, as it illustrates the interconnectedness of water systems and their impact on our environment.",
          subs:["a) What are the main stages of the water cycle?","b) What happens during the evaporation stage?","c) Where does water vapor come from?","d) What forms when water vapor cools and condenses?","e) How does precipitation contribute to the water cycle?","f) What happens to water after it falls to the earth?"] },
        { q:45, text:"Read the following passage and answer the questions given in the end.", co:"CO6",
          passage:"Reading offers numerous benefits that contribute to personal growth and well-being. It provides mental stimulation, which can improve brain function and memory. Regular reading also enhances knowledge and vocabulary, allowing individuals to communicate more effectively. Moreover, reading can serve as an excellent stress-reliever, transporting readers to different worlds and providing a temporary escape from everyday life. Studies have shown that engaging with literature can increase empathy, as readers are exposed to diverse perspectives and experiences. Additionally, reading helps improve focus and concentration, skills that are beneficial in both academic and professional settings. Whether through novels, articles, or essays, the act of reading encourages critical thinking and analytical skills. In a fast-paced digital age, maintaining a reading habit can enhance cognitive abilities and foster a lifelong love of learning. Ultimately, incorporating reading into daily routines not only enriches knowledge but also contributes to emotional well-being and intellectual development.",
          subs:["a) List three benefits of reading mentioned in the passage.","b) How can reading reduce stress?","c) What effect does reading have on focus and concentration?","d) In what way can reading foster empathy?","e) Why is improved vocabulary a benefit of reading?","f) How does reading provide an escape?"] },
        { q:46, text:"Read the following passage and answer the questions given in the end.", co:"CO6",
          passage:"Renewable energy sources, such as solar, wind, and hydroelectric power, are essential for creating a sustainable future. Unlike fossil fuels, which are limited in supply and contribute to environmental degradation, renewable sources are abundant and cleaner for the planet. Solar panels capture sunlight and convert it into electricity, while wind turbines harness wind energy to generate power. Hydroelectric plants utilize the flow of water to produce electricity, demonstrating the versatility of renewable energy. Investing in these energy sources not only helps combat climate change but also promotes energy independence and security. As technology advances, the efficiency and affordability of renewable energy systems continue to improve, making them more accessible to households and businesses. Transitioning to renewable energy is crucial for reducing greenhouse gas emissions and minimizing the impact of global warming. By embracing renewable energy solutions, societies can move toward a greener future and ensure a healthier planet for generations to come.",
          subs:["a) What are three types of renewable energy sources mentioned?","b) Why are renewable energy sources considered more sustainable than fossil fuels?","c) How do solar panels generate electricity?","d) What role do wind turbines play in renewable energy?","e) How can investing in renewable energy combat climate change?","f) What is meant by \"energy independence\"?"] },
        { q:47, text:"Read the following passage and answer the questions given in the end.", co:"CO6",
          passage:"Technology has revolutionized education in countless ways, making learning more interactive and accessible. It provides students with access to a wealth of resources and materials online, allowing for personalized learning experiences. Virtual classrooms enable students to attend lectures from anywhere, breaking geographical barriers. Additionally, interactive simulations and educational software can enhance understanding of complex concepts. While the integration of technology in education offers numerous benefits, it also presents challenges. Issues such as equitable access to devices and the internet can hinder some students' ability to engage fully. Furthermore, maintaining student engagement can be difficult when learning remotely. Educators must find ways to adapt their teaching methods to effectively incorporate technology and ensure that all students have the opportunity to succeed. By leveraging technology thoughtfully, educators can enhance the learning experience and prepare students for a digital future.",
          subs:["a) How has technology transformed education?","b) What are two benefits of using technology in the classroom?","c) What challenges does technology present in education?","d) How can students collaborate using technology?","e) Why is it important for educators to adapt their teaching methods?","f) What role do online resources play in learning?"] },
        { q:48, text:"Read the following passage and answer the questions given at the end.", co:"CO6",
          passage:"There are industries, which have a special demand for child labour because of their nimble fingers, high level of concentration and capacity to work hard at abysmally low wages. The carpet industry in U.P. and Kashmir employs children to make hand-knotted carpets. There are 80,000 child workers in Jammu & Kashmir alone. In Kashmir because of the political unrest, children are forced to work while many schools are shut. Industries like gem cutting and polishing, pottery and glass want to remain competitive by employing children. The truth is that it is poverty which is pushing children into the brutish labour market. We have 260 million people below the poverty line in India, a large number of them are women. Poor and especially woman-headed families have no option but to push their little ones in this hard life in hostile conditions, with no human or labour rights. There is a lobby which argues that there is nothing wrong with children working as long as the environment for work is conducive to learning new skills but studies have shown that the children are made to do boring, repetitive and tedious jobs and are not taught new skills as they grow older. In these hellholes like the sweet shops of the old, there is no hope.",
          subs:["a) Why there is a demand for child labour?","b) Why there are a large number of child labourers in Jammu & Kashmir?","c) According to the passages which are the industries where there is huge demand for child labour?","d) What do you think is the major reason for the evil of child labour?","e) Is there any hope that children while labouring will learn new skills for their better future?","f) What is the central idea of this passage?"] }
    ]
};

// ============================================
// ENGLISH — Year 2025 — Assignment 2
// ============================================
const eng2025A2 = {
    sectionA: [
        { q:1, text:"What is a suffix? Give two examples.", co:"CO4" },
        { q:2, text:"Add prefix to the words: (i) honest (ii) possible", co:"CO4" },
        { q:3, text:"Use -ness as suffix to make two meaningful words.", co:"CO4" },
        { q:4, text:"Define collocation with examples.", co:"CO4" },
        { q:5, text:"Why is vocabulary important in communication? Discuss.", co:"CO4" },
        { q:6, text:"Fill suitable prefix: (i) He was ___ able to complete the task. (ii) The story was ___ believable.", co:"CO4" },
        { q:7, text:"Give two examples of Noun + Noun collocation.", co:"CO4" },
        { q:8, text:"Use pre- as prefix to make two meaningful words.", co:"CO4" },
        { q:9, text:"Fill suitable suffix: (i) She is a very ___ person. (kind) (ii) The weather was ___ . (cloud)", co:"CO4" },
        { q:10, text:"What is a prefix? Give two examples.", co:"CO4" },
        { q:11, text:"What is the purpose of reading?", co:"CO5" },
        { q:12, text:"How does reading improve our knowledge?", co:"CO5" },
        { q:13, text:"How does reading help in developing vocabulary?", co:"CO5" },
        { q:14, text:"What are the challenges faced during reading?", co:"CO5" },
        { q:15, text:"What is skimming? Explain.", co:"CO5" },
        { q:16, text:"What is scanning? Explain.", co:"CO5" },
        { q:17, text:"What is intensive reading?", co:"CO5" },
        { q:18, text:"What is extensive reading?", co:"CO5" },
        { q:19, text:"How can we improve our reading speed?", co:"CO5" },
        { q:20, text:"Why is concentration important in reading?", co:"CO5" },
        { q:21, text:"What is comprehension in reading?", co:"CO6" },
        { q:22, text:"How can we develop communication skills?", co:"CO6" },
        { q:23, text:"Why is grammar important in communication?", co:"CO6" },
        { q:24, text:"What is the importance of reading comprehension?", co:"CO6" },
        { q:25, text:"How to write a summary of a passage?", co:"CO6" },
        { q:26, text:"What is paraphrasing?", co:"CO6" },
        { q:27, text:"Why is critical reading important?", co:"CO6" },
        { q:28, text:"What are the steps of comprehension?", co:"CO6" },
        { q:29, text:"How does comprehension improve writing skills?", co:"CO6" },
        { q:30, text:"What is the role of editing in comprehension?", co:"CO6" }
    ],
    sectionB: [
        { q:31, text:"What is collocation? Explain its types with examples.", co:"CO4" },
        { q:32, text:"Identify 6 prefixes in the following paragraph. Make 2 meaningful words using those prefixes.", co:"CO4",
          passage:"The teacher asked the students to rewrite the essay. The initial draft was unclear. Many students decided to recheck their work. They were uncertain about the topic. The teacher was unhappy with the first attempt. She told them to reconsider their approach. After rethinking, they submitted better essays." },
        { q:33, text:"Do as directed:", co:"CO4",
          subs:["a. Use '-ful' as suffix to make two meaningful words.","b. Use 're-' as prefix to make two meaningful words.","c. She is a very ____ girl. (beauty) (Use suitable suffix)","d. He ____ the story completely. (understand) (Use suitable prefix)","e. The task was ____. (possible) (Use suitable prefix)","f. He showed great ____ . (kind) (Use suitable suffix)"] },
        { q:34, text:"Identify 6 prefixes in the following paragraph. Make 2 meaningful words using those prefixes.", co:"CO4",
          passage:"The project was incomplete due to lack of resources. The team decided to reallocate the tasks. They were unhappy with the progress. They wanted to reevaluate the strategy. The leader was proactive in solving issues. They planned to overcome the challenges." },
        { q:35, text:"Identify 6 suffixes in the following paragraph. Make 2 meaningful words using those suffixes.", co:"CO4",
          passage:"The children were happily playing in the beautiful garden. Their colourful toys were scattered everywhere. The peaceful environment made everyone feel relaxed. The friendly neighbours joined them. The joyful moments were memorable for all." },
        { q:36, text:"What is suffix and prefix? Give four examples of each.", co:"CO4" },
        { q:37, text:"Discuss the importance of reading skills in the English language.", co:"CO5" },
        { q:38, text:"How can we improve our reading skills? Explain with 5 steps.", co:"CO5" },
        { q:39, text:"Describe the process of active reading.", co:"CO5" },
        { q:40, text:"Explain effective reading skills in detail.", co:"CO5" },
        { q:41, text:"What are the gears of reading? Explain.", co:"CO5" },
        { q:42, text:"What skills are required for reading?", co:"CO5" },
        { q:43, text:"Read the passage and answer the questions: (Health and Exercise)", co:"CO6",
          passage:"Regular exercise is important for a healthy life. It helps in maintaining body weight. It improves blood circulation and strengthens muscles. Exercise reduces stress and keeps us energetic. It also prevents diseases like diabetes and heart problems. We should exercise daily for at least 30 minutes. Walking, running, and yoga are good forms of exercise.",
          subs:["a) Why is exercise important?","b) Name two benefits of exercise.","c) What diseases can exercise prevent?","d) How much time should we exercise daily?","e) Name three forms of exercise."] },
        { q:44, text:"Read the passage and answer the questions: (Pollution)", co:"CO6",
          passage:"Pollution is a big problem in today's world. It harms our environment and health. Air pollution causes breathing problems. Water pollution affects marine life. We should reduce pollution by planting more trees. We should also avoid using plastic bags. Recycling is a good way to reduce waste.",
          subs:["a) What is pollution?","b) What does air pollution cause?","c) How does water pollution affect marine life?","d) How can we reduce pollution?","e) Why is recycling important?"] },
        { q:45, text:"Read the passage and answer the questions: (Education)", co:"CO6",
          passage:"Education is the key to success. It helps in personal and professional growth. It develops critical thinking and decision-making skills. Education empowers people to achieve their goals. It also helps in building a better society. Every child should get proper education.",
          subs:["a) What is the importance of education?","b) How does education help individuals?","c) What skills does education develop?","d) How does education help society?","e) Why should every child get education?"] },
        { q:46, text:"Read the passage and answer the questions: (Global Warming)", co:"CO6",
          passage:"Global warming is a serious issue. It is caused by the increase in greenhouse gases. It leads to rising temperatures and melting ice caps. It affects weather patterns and causes natural disasters. We can reduce global warming by planting trees and using renewable energy.",
          subs:["a) What is global warming?","b) What causes global warming?","c) What are the effects of global warming?","d) How can we reduce global warming?","e) What is the role of renewable energy?"] },
        { q:47, text:"Read the passage and answer the questions: (Social Media)", co:"CO6",
          passage:"Social media has changed the way we communicate. It allows us to connect with people worldwide. It is useful for sharing information. However, it also has negative effects. It can cause addiction and spread fake news. We should use social media responsibly.",
          subs:["a) How has social media changed communication?","b) What are the advantages of social media?","c) What are the negative effects of social media?","d) What is fake news?","e) How should we use social media?"] },
        { q:48, text:"Read the passage and answer the questions: (Healthy Food)", co:"CO6",
          passage:"Healthy food is essential for good health. It gives energy and nutrients to our body. Fruits, vegetables, and whole grains are healthy foods. Junk food is harmful to our health. We should eat balanced meals. Drinking plenty of water is also important.",
          subs:["a) Why is healthy food important?","b) Name two healthy foods.","c) Why is junk food harmful?","d) What is a balanced meal?","e) Why is drinking water important?"] }
    ]
};

// ============================================
// ENGLISH — Year 2022 — Assignment 1
// ============================================
const eng2022A1 = {
    sectionA: [
        { q:1, text:"\"Communication is the backbone of any organization.\" Discuss.", co:"CO1" },
        { q:2, text:"What is the meaning of 'channel' in communication?", co:"CO1" },
        { q:3, text:"What is the role of feedback in communication?", co:"CO1" },
        { q:4, text:"What is the difference between formal and informal communication?", co:"CO1" },
        { q:5, text:"How can cultural differences affect communication?", co:"CO1" },
        { q:6, text:"What is group communication? Give an example.", co:"CO1" },
        { q:7, text:"What is mass communication? Give an example.", co:"CO1" },
        { q:8, text:"\"Effective communication leads to personal growth.\" Discuss.", co:"CO1" },
        { q:9, text:"What are the goals of communication?", co:"CO1" },
        { q:10, text:"How can noise affect communication?", co:"CO1" },
        { q:11, text:"What is the meaning of 'eye contact' in non-verbal communication?", co:"CO2" },
        { q:12, text:"What is the role of posture in non-verbal communication?", co:"CO2" },
        { q:13, text:"What is the meaning of 'gestures'? Give an example.", co:"CO2" },
        { q:14, text:"What is the importance of personal space in communication?", co:"CO2" },
        { q:15, text:"What is the role of tone in communication?", co:"CO2" },
        { q:16, text:"\"Appearance is a part of non-verbal communication.\" Discuss.", co:"CO2" },
        { q:17, text:"How does facial expression convey emotions?", co:"CO2" },
        { q:18, text:"What is the difference between verbal and non-verbal communication?", co:"CO2" },
        { q:19, text:"What are the functions of non-verbal communication?", co:"CO2" },
        { q:20, text:"How does silence play a role in non-verbal communication?", co:"CO2" },
        { q:21, text:"\"Vocabulary is a key to success.\" Discuss.", co:"CO3" },
        { q:22, text:"Give meaning of the words: Optimism and Pessimism.", co:"CO3" },
        { q:23, text:"Use these words in a sentence: Inspire and Motivate.", co:"CO3" },
        { q:24, text:"Use these words in a sentence: Achievement and Success.", co:"CO3" },
        { q:25, text:"Give meaning of the words: Determination and Discipline.", co:"CO3" },
        { q:26, text:"How does vocabulary help in career growth?", co:"CO3" },
        { q:27, text:"Give Antonym of Love and Peace.", co:"CO3" },
        { q:28, text:"Give meaning and use it in a sentence of Unity.", co:"CO3" },
        { q:29, text:"Why is a good vocabulary important for students?", co:"CO3" },
        { q:30, text:"Give Synonym of Knowledge and Integrity.", co:"CO3" }
    ],
    sectionB: [
        { q:31, text:"Explain the communication process in detail.", co:"CO1" },
        { q:32, text:"What are the types of communication? Explain.", co:"CO1" },
        { q:33, text:"What is feedback? Why is it important in communication?", co:"CO1" },
        { q:34, text:"What are the barriers to effective communication?", co:"CO1" },
        { q:35, text:"How can communication barriers be overcome?", co:"CO1" },
        { q:36, text:"What are the 7C's of communication? Explain.", co:"CO1" },
        { q:37, text:"What is verbal communication? Give examples.", co:"CO2" },
        { q:38, text:"What is non-verbal communication? Give examples.", co:"CO2" },
        { q:39, text:"How does body language affect communication?", co:"CO2" },
        { q:40, text:"Why is non-verbal communication important in daily life?", co:"CO2" },
        { q:41, text:"Explain the different types of non-verbal communication.", co:"CO2" },
        { q:42, text:"How can we improve non-verbal communication?", co:"CO2" },
        { q:43, text:"Give meaning of the words: a) Innovation b) Creativity c) Excellence d) Integrity.", co:"CO3" },
        { q:44, text:"Use the words as a sentence: a) Inspire b) Achieve c) Courage d) Wisdom.", co:"CO3" },
        { q:45, text:"Fill in the blanks:", co:"CO3", subs:["a) She is a ___ of inspiration.","b) We should always speak the ___.","c) Hard work is the key to ___.","d) We should respect our ___."] },
        { q:46, text:"Match the following with Synonyms:", co:"CO3", subs:["a) Happy — Sad","b) Brave — Fearful","c) Kind — Cruel","d) Wise — Intelligent"] },
        { q:47, text:"Give meaning of the following words: a) Success b) Failure c) Happiness d) Peace.", co:"CO3" },
        { q:48, text:"Use following words in a sentence: a) Freedom b) Equality c) Justice d) Unity.", co:"CO3" }
    ]
};

// ============================================
// ENGLISH — Year 2023 — Assignment 1
// ============================================
const eng2023A1 = {
    sectionA: [
        { q:1, text:"\"Communication is the foundation of human relationships.\" Discuss.", co:"CO1" },
        { q:2, text:"What is the role of a sender in communication?", co:"CO1" },
        { q:3, text:"What is the role of a receiver in communication?", co:"CO1" },
        { q:4, text:"What is meant by a 'message' in communication?", co:"CO1" },
        { q:5, text:"How can language be a barrier in communication?", co:"CO1" },
        { q:6, text:"What is formal communication? Give an example.", co:"CO1" },
        { q:7, text:"What is informal communication? Give an example.", co:"CO1" },
        { q:8, text:"\"Group communication helps in teamwork.\" Discuss.", co:"CO1" },
        { q:9, text:"Define the term 'feedback' in communication.", co:"CO1" },
        { q:10, text:"What are psychological barriers in communication?", co:"CO1" },
        { q:11, text:"What is the meaning of 'facial expressions' in non-verbal communication?", co:"CO2" },
        { q:12, text:"What is the importance of posture in communication?", co:"CO2" },
        { q:13, text:"What are hand gestures? How do they help in communication?", co:"CO2" },
        { q:14, text:"What is the role of eye contact in communication?", co:"CO2" },
        { q:15, text:"What is the meaning of 'proxemics' in communication?", co:"CO2" },
        { q:16, text:"\"Physical appearance plays a role in communication.\" Discuss.", co:"CO2" },
        { q:17, text:"What is the difference between formal and informal body language?", co:"CO2" },
        { q:18, text:"How does the tone of voice affect communication?", co:"CO2" },
        { q:19, text:"What is the role of silence in communication?", co:"CO2" },
        { q:20, text:"What are the advantages of non-verbal communication?", co:"CO2" },
        { q:21, text:"\"Vocabulary is a tool for effective communication.\" Discuss.", co:"CO3" },
        { q:22, text:"Give meaning of the words: Potential and Challenge.", co:"CO3" },
        { q:23, text:"Use these words in a sentence: Dedication and Honesty.", co:"CO3" },
        { q:24, text:"Use these words in a sentence: Wisdom and Knowledge.", co:"CO3" },
        { q:25, text:"Give meaning of the words: Ambition and Success.", co:"CO3" },
        { q:26, text:"How does vocabulary help in daily communication?", co:"CO3" },
        { q:27, text:"Give Antonym of Courage and Strength.", co:"CO3" },
        { q:28, text:"Give meaning and use it in a sentence of Unity.", co:"CO3" },
        { q:29, text:"Why is vocabulary important for professional success?", co:"CO3" },
        { q:30, text:"Give Synonym of Happiness and Progress.", co:"CO3" }
    ],
    sectionB: [
        { q:31, text:"Explain the communication process with a diagram.", co:"CO1" },
        { q:32, text:"What are the different types of communication? Explain.", co:"CO1" },
        { q:33, text:"What is feedback? Why is it important in communication?", co:"CO1" },
        { q:34, text:"What are the common barriers to communication?", co:"CO1" },
        { q:35, text:"How can we remove communication barriers?", co:"CO1" },
        { q:36, text:"What is the 7C's of communication? Explain.", co:"CO1" },
        { q:37, text:"What is verbal communication? Give examples.", co:"CO2" },
        { q:38, text:"What is non-verbal communication? Give examples.", co:"CO2" },
        { q:39, text:"What is the role of body language in communication?", co:"CO2" },
        { q:40, text:"Why is non-verbal communication important?", co:"CO2" },
        { q:41, text:"Explain the different types of non-verbal communication.", co:"CO2" },
        { q:42, text:"How can we improve non-verbal communication skills?", co:"CO2" },
        { q:43, text:"Give meaning of the words: a) Perseverance b) Integrity c) Commitment d) Excellence.", co:"CO3" },
        { q:44, text:"Use the words as a sentence: a) Inspire b) Achieve c) Courage d) Wisdom.", co:"CO3" },
        { q:45, text:"Fill in the blanks:", co:"CO3", subs:["a) She is a ___ of inspiration.","b) We should always speak the ___.","c) Hard work is the key to ___.","d) We should respect our ___."] },
        { q:46, text:"Match the following with Synonyms:", co:"CO3", subs:["a) Happy — Sad","b) Brave — Fearful","c) Kind — Cruel","d) Wise — Intelligent"] },
        { q:47, text:"Give meaning of the following words: a) Success b) Failure c) Happiness d) Peace.", co:"CO3" },
        { q:48, text:"Use following words in a sentence: a) Freedom b) Equality c) Justice d) Unity.", co:"CO3" }
    ]
};

// ============================================
// ENGLISH — Year 2024 — Assignment 1
// ============================================
const eng2024A1 = {
    sectionA: [
        { q:1, text:"\"Communication is the integral part of our life\". Discuss.", co:"CO1" },
        { q:2, text:"Define the term 'feedback' in the context of communication.", co:"CO1" },
        { q:3, text:"What is the role of 'encoding' in the communication process?", co:"CO1" },
        { q:4, text:"Difference between Sender and the Receiver.", co:"CO1" },
        { q:5, text:"How can stress act as a psychological barrier in communication?", co:"CO1" },
        { q:6, text:"Why Formal communication is regarded as official communication?", co:"CO1" },
        { q:7, text:"What is the role of noise in the process of communication?", co:"CO1" },
        { q:8, text:"\"Intrapersonal communication leads to the personal growth of individual\". Discuss.", co:"CO1" },
        { q:9, text:"Difference between encoding and decoding.", co:"CO1" },
        { q:10, text:"Describe one way in which cultural barriers can impact communication.", co:"CO1" },
        { q:11, text:"What do you mean by Kinesics?", co:"CO2" },
        { q:12, text:"What is the difference between Verbal and Non-Verbal communication?", co:"CO2" },
        { q:13, text:"What are the advantages of paralanguage?", co:"CO2" },
        { q:14, text:"What does avoiding eye contact generally suggest about a person's feelings?", co:"CO2" },
        { q:15, text:"What do you mean by Proxemics?", co:"CO2" },
        { q:16, text:"\"Non-Verbal communication plays a very important role in day-to-day life\". Explain.", co:"CO2" },
        { q:17, text:"How does social gatherings play an important role in terms of Proxemics?", co:"CO2" },
        { q:18, text:"Explain how pitch variations can affect the meaning of a sentence.", co:"CO2" },
        { q:19, text:"How does body language interpret our language of communication?", co:"CO2" },
        { q:20, text:"How can a change in tone affect the meaning of a message in paralanguage?", co:"CO2" },
        { q:21, text:"\"Vocabulary plays a vital role in English language\". Explain.", co:"CO3" },
        { q:22, text:"Give meaning of the words: Inevitable and Entrepreneur.", co:"CO3" },
        { q:23, text:"Use these words in a sentence: Eventually and Overtly.", co:"CO3" },
        { q:24, text:"Use these words in a sentence: Modest and Heritage.", co:"CO3" },
        { q:25, text:"Give meaning of the words: Feasibility and Collapse.", co:"CO3" },
        { q:26, text:"What role does vocabulary play in personal expression and creativity?", co:"CO3" },
        { q:27, text:"Give Antonym of Inglorious and Oppressive.", co:"CO3" },
        { q:28, text:"Give meaning and use it in a sentence of Impose.", co:"CO3" },
        { q:29, text:"Why is a strong vocabulary essential for effective communication?", co:"CO3" },
        { q:30, text:"Give Synonym of Hazardous and Proficient.", co:"CO3" }
    ],
    sectionB: [
        { q:31, text:"Discuss the process of communication in detail.", co:"CO1" },
        { q:32, text:"Explain different types of communication.", co:"CO1" },
        { q:33, text:"Discuss the role of feedback in the communication process. How does it affect the effectiveness of communication?", co:"CO1" },
        { q:34, text:"Explain common barriers to effective communication in the workplace.", co:"CO1" },
        { q:35, text:"How noise act as a barrier in communication?", co:"CO1" },
        { q:36, text:"Discuss types of Barriers in detail.", co:"CO1" },
        { q:37, text:"What is the difference between Verbal and Non-Verbal communication?", co:"CO2" },
        { q:38, text:"Explain the role of body language in non-verbal communication and provide examples of how different body language cues can alter the meaning of a message.", co:"CO2" },
        { q:39, text:"Discuss the concept of paralanguage and its role in non-verbal communication. How do tone, pitch, and volume of voice contribute to the meaning of spoken words?", co:"CO2" },
        { q:40, text:"Define non-verbal communication and discuss its importance in interpersonal interactions.", co:"CO2" },
        { q:41, text:"Write in detail about non-verbal cues in detail.", co:"CO2" },
        { q:42, text:"Describe how non-verbal communication can be used to build rapport and establish trust in professional relationships.", co:"CO2" },
        { q:43, text:"Give meaning of the words: a) Impose b) Tactics c) Dismal d) Lethal.", co:"CO3" },
        { q:44, text:"Use the words as a sentence: a) Ardent b) Polymath c) Hinder d) Magnate.", co:"CO3" },
        { q:45, text:"Fill in the blanks:", co:"CO3", subs:["a) He was a ___ smuggler and gambler.","b) Einstein was the great ___ of Quantum Physics.","c) Air Pollution is a ___ to the city.","d) We must preserve our cultural ___."] },
        { q:46, text:"Match the following with Synonyms:", co:"CO3", subs:["a) Dismal — Extremely Happy","b) Elated — Inborn","c) Innate — Visualize","d) Envision — Gloomy"] },
        { q:47, text:"Give meaning of the following words: a) Critical b) Tremendous c) Decade d) Remote.", co:"CO3" },
        { q:48, text:"Use following words in a sentence: a) Renaissance b) Impromptu c) Consensus d) Secluded.", co:"CO3" }
    ]
};

// ============================================
// ENGLISH — Year 2025 — Assignment 1
// ============================================
const eng2025A1 = {
    sectionA: [
        { q:1, text:"What is communication? Explain its importance.", co:"CO1" },
        { q:2, text:"Define the term 'encoding' in communication.", co:"CO1" },
        { q:3, text:"Define the term 'decoding' in communication.", co:"CO1" },
        { q:4, text:"What is the role of the receiver in communication?", co:"CO1" },
        { q:5, text:"What are physical barriers in communication? Give an example.", co:"CO1" },
        { q:6, text:"What is formal communication? Give an example.", co:"CO1" },
        { q:7, text:"What is informal communication? Give an example.", co:"CO1" },
        { q:8, text:"\"Interpersonal communication helps in building relationships.\" Discuss.", co:"CO1" },
        { q:9, text:"What is the difference between verbal and non-verbal communication?", co:"CO1" },
        { q:10, text:"What are semantic barriers in communication?", co:"CO1" },
        { q:11, text:"What is the meaning of 'gestures' in non-verbal communication?", co:"CO2" },
        { q:12, text:"What is body language? Give an example.", co:"CO2" },
        { q:13, text:"What is eye contact? Why is it important?", co:"CO2" },
        { q:14, text:"What is facial expression? Give an example.", co:"CO2" },
        { q:15, text:"What are hand gestures? Give an example.", co:"CO2" },
        { q:16, text:"\"Posture tells a lot about a person's attitude.\" Discuss.", co:"CO2" },
        { q:17, text:"What is personal space in communication?", co:"CO2" },
        { q:18, text:"What is the importance of non-verbal communication?", co:"CO2" },
        { q:19, text:"How does appearance affect communication?", co:"CO2" },
        { q:20, text:"What is the difference between tone and pitch?", co:"CO2" },
        { q:21, text:"\"Vocabulary helps in expressing thoughts clearly.\" Discuss.", co:"CO3" },
        { q:22, text:"Give meaning of the words: Prosperity and Integrity.", co:"CO3" },
        { q:23, text:"Use these words in a sentence: Diligent and Humble.", co:"CO3" },
        { q:24, text:"Use these words in a sentence: Courage and Wisdom.", co:"CO3" },
        { q:25, text:"Give meaning of the words: Perseverance and Tolerance.", co:"CO3" },
        { q:26, text:"How does vocabulary help in professional communication?", co:"CO3" },
        { q:27, text:"Give Antonym of Honest and Brave.", co:"CO3" },
        { q:28, text:"Give meaning and use it in a sentence of Compassion.", co:"CO3" },
        { q:29, text:"Why is vocabulary important in public speaking?", co:"CO3" },
        { q:30, text:"Give Synonym of Generous and Intelligent.", co:"CO3" }
    ],
    sectionB: [
        { q:31, text:"Explain the communication process with a diagram.", co:"CO1" },
        { q:32, text:"What are the types of communication? Explain each.", co:"CO1" },
        { q:33, text:"What is feedback? Why is it important in communication?", co:"CO1" },
        { q:34, text:"Explain any four barriers of communication with examples.", co:"CO1" },
        { q:35, text:"How can we overcome communication barriers?", co:"CO1" },
        { q:36, text:"What is the 7C's of communication? Explain.", co:"CO1" },
        { q:37, text:"What is the difference between verbal and non-verbal communication?", co:"CO2" },
        { q:38, text:"Explain the role of body language in non-verbal communication.", co:"CO2" },
        { q:39, text:"What is paralanguage? How does it affect communication?", co:"CO2" },
        { q:40, text:"Why is non-verbal communication important in daily life?", co:"CO2" },
        { q:41, text:"Explain different types of non-verbal communication.", co:"CO2" },
        { q:42, text:"How can we use non-verbal communication effectively?", co:"CO2" },
        { q:43, text:"Give meaning of the words: a) Resilience b) Ambition c) Patience d) Gratitude.", co:"CO3" },
        { q:44, text:"Use the words as a sentence: a) Inspire b) Achieve c) Courage d) Wisdom.", co:"CO3" },
        { q:45, text:"Fill in the blanks:", co:"CO3", subs:["a) She has a lot of ___ to succeed in life.","b) We should always speak the ___.","c) Hard work is the key to ___.","d) We should respect our ___."] },
        { q:46, text:"Match the following with Synonyms:", co:"CO3", subs:["a) Happy — Sad","b) Brave — Fearful","c) Kind — Cruel","d) Wise — Intelligent"] },
        { q:47, text:"Give meaning of the following words: a) Success b) Failure c) Happiness d) Peace.", co:"CO3" },
        { q:48, text:"Use following words in a sentence: a) Freedom b) Equality c) Justice d) Unity.", co:"CO3" }
    ]
};

// ============================================
// Master Subject Config
// ============================================
const subjects = {
    "c-language": {
        name: "C Language",
        code: "",
        courseOutcomes: cLanguageCO,
        data: {
            "2022": { "1": cLangA1, "2": cLangA2 },
            "2023": { "1": cLangA1, "2": cLangA2 },
            "2024": { "1": cLangA1, "2": cLangA2 },
            "2025": { "1": cLangA1, "2": cLangA2 }
        }
    },
    "english": {
        name: "Foundation Course in English-I",
        code: "AEC-24101",
        courseOutcomes: englishCO,
        data: {
            "2022": { "1": eng2022A1, "2": eng2022A2 },
            "2023": { "1": eng2023A1, "2": eng2023A2 },
            "2024": { "1": eng2024A1, "2": eng2024A2 },
            "2025": { "1": eng2025A1, "2": eng2025A2 }
        }
    }
};
